name: CI Testing
on:
  schedule: 
   - cron: '35 20 * * 3'
  push:
    branches:
      - "**"
  pull_request:
    types: ['opened']
jobs:
  lint: 
    name: 'Lint tests folder'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependecies
      working-directory: ./lesson23-24
      run: | 
        echo "LINT TESTS"
        npm ci
    - name: Run lint
      working-directory: ./lesson23-24
      run: npm run lint
  tests-playwright: 
    name: 'Playwright E2E Tests'
    needs: lint
    if: success() || failure()
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-jammy
    steps:
    - uses: actions/checkout@v3
    - name: Install dependecies
      run: npm ci
    - name: Run Playwright tests
      working-directory: ./lesson23-24
      run: npm run playw:test:chromium  
      env:
        TESTOMATIO_CREATE: ${{ vars.TESTOMATIO_CREATE }}
        TESTOMATIO: ${{ vars.TESTOMATIO }}
        user: ${{ vars.user }}
        password: ${{ vars.password }}  
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report-e2e
        path: |
          ./playwright-report/
          ./test-results/
        retention-days: 30
  test-cypress: 
    name: 'Cypress tests'
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.12.0-chrome-131.0.6778.139-1-ff-133.0.3-edge-131.0.2903.99-1
      options: --user 1001
    steps:
      - uses: actions/checkout@v3
      - name: Install dependecies
        working-directory: ./lesson17
        run: npm ci
      - name: Run Cypress tests
        working-directory: ./lesson17
        run: npm run cy:run:prod  --browser chrome

        
